package com.ccrt.onlineshop.enums;

public enum MessageCode {
  USER_NOT_FOUND, FIRST_NAME_NOT_VALID, LAST_NAME_NOT_VALID, EMAIL_NOT_VALID, PASSWORD_NOT_VALID, FORBIDDEN,
  BAD_REQUEST, WRONG_PASSWORD, PASSWORD_UPDATE_SUCCESSFUL, FILE_CREATION_ERROR,
  PASSWORD_RESET_SUCCESSFUL, PASSWORD_RESET_CODE_MISMATCH, USER_OTP_SERVICE_BLOCKED, OTP_CODE_EXPIRED, OTP_CODE_MISMATCH
}
