package com.ccrt.onlineshop.enums;

public enum MessageCode {
  USER_NOT_FOUND, FIRST_NAME_NOT_VALID, LAST_NAME_NOT_VALID, EMAIL_NOT_VALID, PASSWORD_NOT_VALID, FORBIDDEN,
  BAD_REQUEST, WRONG_PASSWORD, PASSWORD_UPDATE_SUCCESSFUL, FILE_CREATION_ERROR, TITLE_NOT_VALID, CATEGORY_NOT_FOUND,
  SUB_CATEGORY_NOT_FOUND, PRODUCT_NOT_FOUND, ADDRESS_NOT_FOUND, PRICE_NOT_VALID, TOTAL_ENTITIES_NOT_VALID,
  USAGE_STATUS_NOT_VALID, RATING_ALREADY_EXISTS, RATING_NOT_FOUND, STATUS_NOT_VALID, DONOR_NAME_NOT_VALID,
  PHONE_NO_NOT_VALID, PRODUCT_TITLE_NOT_VALID, NUM_ITEMS_NOT_VALID, ADDRESS_NOT_VALID, DESCRIPTION_NOT_VALID,
  DURATION_NOT_VALID, PRICE_REDUCTION_PERCENTAGE_NOT_VALID, CAMPAIGN_NOT_FOUND, COVER_NOT_FOUND,
  CAMPAIGN_CANNOT_BE_DELETED, DUPLICATE_EMAIL,
  IMAGE_NOT_VALID, INVALID_TYPE, ORDER_NOT_FOUND, ORDER_STATUS_ORDER_NOT_VALID, DONATION_NOT_FOUND, DATE_NOT_VALID,
  PASSWORD_RESET_SUCCESSFUL, PASSWORD_RESET_CODE_MISMATCH, USER_OTP_SERVICE_BLOCKED, OTP_CODE_EXPIRED, OTP_CODE_MISMATCH
}
